const path = require("path");

const options = {
  openapi: null, // Enable/Disable OpenAPI. By default is null
  language: "en-US", // Change response language. By default is 'en-US'
  disableLogs: false, // Enable/Disable logs. By default is false
  autoHeaders: true, // Enable/Disable automatic headers capture. By default is true
  autoQuery: true, // Enable/Disable automatic query capture. By default is true
  autoBody: true, // Enable/Disable automatic body capture. By default is true
};

const swaggerAutogen = require("swagger-autogen")(options);

const doc = {
  info: {
    version: "1.0.0",
    title: "My API",
    description:
      "Documentation automatically generated by the <b>swagger-autogen</b> module.",
  },
  host: "localhost:3000",
  // basePath: '/api/employee',
  schemes: ["http"],
  consumes: ["application/json"],
  produces: ["application/json"],
  definition: {
    insertEmployee: {
      id: 4,
      userId: "no.1",
      jobTitleName: "Cricketer",
      firstName: "Virat",
      lastName: "Kohli",
      preferredFullName: "Virat Kohli",
      employeeCode: "E4",
      region: "IN",
      phoneNumber: "408-22225622",
      emailAddress: "viratkohli@gmail.com",
    },
    updateEmployee: {
      firstName: "Virat Kohli",
    },
  },
};

const outputFile = "./swagger-output.json";
const endpointsFiles = ["routes/employees.router.js"];

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
  require("../db"); // Your project's root file
});
